### PR TITLE
18 u2 hotelzimmer auswahl frontend

### LINKED ISSUE #18: U2 - Hotelzimmer Auswahl - Frontend

### PR DESCRIPTION
**Pull request by tobiasr97**
Added Frontend Page to search by time time period for available rooms.

### CODE REVIEW

**Review by alexisschaffer — CHANGES_REQUESTED** [review]
Hey something with this div: ```<div data-v-10cb804c="" class="description">Doppelbett mit hervorragender Aussicht auf die Innenstadt!</div>``` is not working properly, when I scroll down it goes away.

image

Also people may be more used to have the day number before the month in german.

**Comment by tobiasr97** [comment]
I agree with you. The description will be removed anyway later, because we have no description. I will  do this now and will check the localisation options of the calendar too, thanks.

**Comment by tobiasr97** [comment]
I have checked the description and it actually was a bug, when the lazily loaded image was not loaded yet and therefore the container did not have a width -> the description div, as it is positioned from the bottom, looked like this. This got fixed.

The localisation of the calendar would be possible, but the current solution should simply use the default Intl.DateTimeFormat, which most probably in your case is english? I could not find an answer in the ionic docs, as it only states it uses a default one, but not exactly which. On my system it is the default german format. @alexisschaffer Plese check on your system to be sure with e.g. "new Intl.DateTimeFormat().format(new Date())" int he console. If it takes the default one, I would stick to this solution instead of forceing the german format to everyone.

**Comment by alexisschaffer** [comment]
Yes my browser is in english this was the problem. All good then.

**Review by alexisschaffer — APPROVED** [review]
All good now

**Comment by tobiasr97** [comment]
Created a new Branch, feature/U2/8-hotelzimmer-auswahl, where the frontend and backend of U2 got merged. This branch now needs to get merged into main!

**Pull request closed without merging**
